const initState = [
  { NomMarca: 'Marcas | Brands', CodMarca: '0' },
  { NomMarca: '<<OTROS>>', CodMarca: '1000' },
  { NomMarca: 'CATERPILLAR', CodMarca: '1' },
  { NomMarca: 'JOHN DEERE', CodMarca: '16' },
  { NomMarca: 'KOMATSU', CodMarca: '4' },
  { NomMarca: 'CNH', CodMarca: '289' },
  { NomMarca: 'CUMMINS', CodMarca: '6' },
  { NomMarca: 'ACT', CodMarca: '79' },
  { NomMarca: 'ADCO', CodMarca: '199' },
  { NomMarca: 'AEROEQUIP', CodMarca: '384' },
  { NomMarca: 'AEROQUIP', CodMarca: '389' },
  { NomMarca: 'AGCO', CodMarca: '96' },
  { NomMarca: 'AGRALE', CodMarca: '317' },
  { NomMarca: 'ALLIANT', CodMarca: '320' },
  { NomMarca: 'ALLIS CHALMERS', CodMarca: '99' },
  { NomMarca: 'ALLISON', CodMarca: '299' },
  { NomMarca: 'ALTRONIC', CodMarca: '262' },
  { NomMarca: 'AMMANN', CodMarca: '313' },
  { NomMarca: 'APPLETON', CodMarca: '399' },
  { NomMarca: 'ARC', CodMarca: '255' },
  { NomMarca: 'ARCA', CodMarca: '352' },
  { NomMarca: 'ASTEC', CodMarca: '100' },
  { NomMarca: 'ATLAS', CodMarca: '288' },
  { NomMarca: 'ATLAS COPCO', CodMarca: '58' },
  { NomMarca: 'BAKER', CodMarca: '101' },
  { NomMarca: 'BALDWIN', CodMarca: '60' },
  { NomMarca: 'BARKO', CodMarca: '290' },
  { NomMarca: 'BCA', CodMarca: '348' },
  { NomMarca: 'BD', CodMarca: '196' },
  { NomMarca: 'BEICRUZ', CodMarca: '86' },
  { NomMarca: 'BERCO', CodMarca: '215' },
  { NomMarca: 'BLACK CAT', CodMarca: '73' },
  { NomMarca: 'BLUMAQ', CodMarca: '308' },
  { NomMarca: 'BOBCAT', CodMarca: '71' },
  { NomMarca: 'BOMAG', CodMarca: '287' },
  { NomMarca: 'BONEM', CodMarca: '44' },
  { NomMarca: 'BORG WARNER', CodMarca: '102' },
  { NomMarca: 'BORG-WARNER', CodMarca: '140' },
  { NomMarca: 'BORGWARNER', CodMarca: '249' },
  { NomMarca: 'BOSCH', CodMarca: '61' },
  { NomMarca: 'BOWER', CodMarca: '38' },
  { NomMarca: 'BRASIL', CodMarca: '213' },
  { NomMarca: 'BRODERSON', CodMarca: '103' },
  { NomMarca: 'BROOKVILLE', CodMarca: '104' },
  { NomMarca: 'BROTHER', CodMarca: '259' },
  { NomMarca: 'CAMECO', CodMarca: '20' },
  { NomMarca: 'CAMERON', CodMarca: '396' },
  { NomMarca: 'CAMLOCK', CodMarca: '387' },
  { NomMarca: 'CARLIS', CodMarca: '232' },
  { NomMarca: 'CARRARO', CodMarca: '97' },
  { NomMarca: 'CASE', CodMarca: '7' },
  { NomMarca: 'CASE AGRICOLA', CodMarca: '221' },
  { NomMarca: 'CASE CONSTRUCCION', CodMarca: '223' },
  { NomMarca: 'CATERPILLAR FORKLIFT', CodMarca: '302' },
  { NomMarca: 'CGR', CodMarca: '193' },
  { NomMarca: 'CHAMPION', CodMarca: '312' },
  { NomMarca: 'CHARLYNN', CodMarca: '294' },
  { NomMarca: 'CHINA', CodMarca: '307' },
  { NomMarca: 'CHRYSLER', CodMarca: '105' },
  { NomMarca: 'CIVEMASA', CodMarca: '202' },
  { NomMarca: 'CLAAS', CodMarca: '40' },
  { NomMarca: 'CLARK', CodMarca: '106' },
  { NomMarca: 'CLARK HURTH', CodMarca: '107' },
  { NomMarca: 'CLASSIC CAT', CodMarca: '15' },
  { NomMarca: 'CLEVIT', CodMarca: '194' },
  { NomMarca: 'CLEVITE', CodMarca: '381' },
  { NomMarca: 'CMP', CodMarca: '209' },
  { NomMarca: 'COFLEX', CodMarca: '388' },
  { NomMarca: 'COHIDREX', CodMarca: '243' },
  { NomMarca: 'COMMERCIAL', CodMarca: '296' },
  { NomMarca: 'COMPRESOR', CodMarca: '239' },
  { NomMarca: 'CONCENTRIC', CodMarca: '252' },
  { NomMarca: 'CONTINENTAL ENGINE', CodMarca: '108' },
  { NomMarca: 'COVENTRY CLIMAX', CodMarca: '109' },
  { NomMarca: 'CRC EVANS', CodMarca: '48' },
  { NomMarca: 'CROSBY', CodMarca: '30' },
  { NomMarca: 'CROWN', CodMarca: '90' },
  { NomMarca: 'CRW', CodMarca: '89' },
  { NomMarca: 'CTP', CodMarca: '2' },
  { NomMarca: 'DAEWOO', CodMarca: '110' },
  { NomMarca: 'DANA', CodMarca: '111' },
  { NomMarca: 'DAVID BROWN', CodMarca: '401' },
  { NomMarca: 'DAYCO', CodMarca: '112' },
  { NomMarca: 'DEESTONE', CodMarca: '258' },
  { NomMarca: 'DELCO REMY', CodMarca: '217' },
  { NomMarca: 'DELPHI', CodMarca: '366' },
  { NomMarca: 'DENSO', CodMarca: '365' },
  { NomMarca: 'DETROIT', CodMarca: '27' },
  { NomMarca: 'DEUTZ', CodMarca: '225' },
  { NomMarca: 'DHS', CodMarca: '338' },
  { NomMarca: 'DISA', CodMarca: '192' },
  { NomMarca: 'DITCH WITCH', CodMarca: '113' },
  { NomMarca: 'DODGE', CodMarca: '383' },
  { NomMarca: 'DONALDSON', CodMarca: '41' },
  { NomMarca: 'DOOSAN', CodMarca: '197' },
  { NomMarca: 'DRADALL', CodMarca: '122' },
  { NomMarca: 'DRESEL', CodMarca: '114' },
  { NomMarca: 'DRESSER', CodMarca: '34' },
  { NomMarca: 'DREXEL', CodMarca: '141' },
  { NomMarca: 'DTR', CodMarca: '274' },
  { NomMarca: 'DYNAHOE', CodMarca: '115' },
  { NomMarca: 'DYNAPAC', CodMarca: '25' },
  { NomMarca: 'EAGLE PITCHER', CodMarca: '116' },
  { NomMarca: 'EATON', CodMarca: '43' },
  { NomMarca: 'EPIROC', CodMarca: '310' },
  { NomMarca: 'ESCO', CodMarca: '375' },
  { NomMarca: 'EUCLID', CodMarca: '279' },
  { NomMarca: 'FAG', CodMarca: '19' },
  { NomMarca: 'FARMATRAC', CodMarca: '117' },
  { NomMarca: 'FARMTRAC', CodMarca: '142' },
  { NomMarca: 'FATE', CodMarca: '85' },
  { NomMarca: 'FDC', CodMarca: '334' },
  { NomMarca: 'FEDERAL MOGUL', CodMarca: '191' },
  { NomMarca: 'FERMEC', CodMarca: '45' },
  { NomMarca: 'FG WILSON', CodMarca: '321' },
  { NomMarca: 'FIAT ALLIS', CodMarca: '12' },
  { NomMarca: 'FILLRITE', CodMarca: '407' },
  { NomMarca: 'FILTERMART', CodMarca: '49' },
  { NomMarca: 'FINI LAGER', CodMarca: '81' },
  { NomMarca: 'FLEETGUARD', CodMarca: '66' },
  { NomMarca: 'FMC', CodMarca: '190' },
  { NomMarca: 'FORD', CodMarca: '46' },
  { NomMarca: 'FORD OEM', CodMarca: '50' },
  { NomMarca: 'FORUM', CodMarca: '404' },
  { NomMarca: 'FP', CodMarca: '233' },
  { NomMarca: 'FP-DIESEL', CodMarca: '74' },
  { NomMarca: 'FUCHS', CodMarca: '376' },
  { NomMarca: 'FUJIAN', CodMarca: '273' },
  { NomMarca: 'FUNK MFG', CodMarca: '118' },
  { NomMarca: 'FURUKAWA', CodMarca: '342' },
  { NomMarca: 'GAC', CodMarca: '269' },
  { NomMarca: 'GALION', CodMarca: '119' },
  { NomMarca: 'GARDNER DENVER', CodMarca: '390' },
  { NomMarca: 'GARRET', CodMarca: '343' },
  { NomMarca: 'GASO', CodMarca: '391' },
  { NomMarca: 'GATES', CodMarca: '241' },
  { NomMarca: 'GEHL', CodMarca: '120' },
  { NomMarca: 'GEN', CodMarca: '189' },
  { NomMarca: 'GENERADOR', CodMarca: '260' },
  { NomMarca: 'GENERAL MOTORS', CodMarca: '121' },
  { NomMarca: 'GENIE', CodMarca: '291' },
  { NomMarca: 'GHINASSI', CodMarca: '75' },
  { NomMarca: 'GMB', CodMarca: '347' },
  { NomMarca: 'GRADALL', CodMarca: '143' },
  { NomMarca: 'GREENSTAR', CodMarca: '344' },
  { NomMarca: 'GROVE', CodMarca: '5' },
  { NomMarca: 'GROVE CRANE', CodMarca: '123' },
  { NomMarca: 'HALDEX', CodMarca: '227' },
  { NomMarca: 'HALLA', CodMarca: '323' },
  { NomMarca: 'HAMM', CodMarca: '361' },
  { NomMarca: 'HARLO', CodMarca: '124' },
  { NomMarca: 'HARRISON', CodMarca: '125' },
  { NomMarca: 'HATZ', CodMarca: '226' },
  { NomMarca: 'HAULOTTE', CodMarca: '341' },
  { NomMarca: 'HAWK INDUSTRIES', CodMarca: '385' },
  { NomMarca: 'HENSLEY', CodMarca: '200' },
  { NomMarca: 'HERCULES', CodMarca: '13' },
  { NomMarca: 'HERRAMIENTA', CodMarca: '214' },
  { NomMarca: 'HILTI', CodMarca: '398' },
  { NomMarca: 'HINO', CodMarca: '32' },
  { NomMarca: 'HITACHI', CodMarca: '51' },
  { NomMarca: 'HOBBS', CodMarca: '246' },
  { NomMarca: 'HOLDWELL', CodMarca: '237' },
  { NomMarca: 'HOLSET', CodMarca: '283' },
  { NomMarca: 'HONDA', CodMarca: '212' },
  { NomMarca: 'HONDA MOTORES', CodMarca: '356' },
  { NomMarca: 'HOTSTART', CodMarca: '261' },
  { NomMarca: 'HUBER', CodMarca: '126' },
  { NomMarca: 'HUSQVARNA CONSTRUCCION', CodMarca: '358' },
  { NomMarca: 'HUSQVARNA GARDINERIA', CodMarca: '357' },
  { NomMarca: 'HYDREMA', CodMarca: '127' },
  { NomMarca: 'HYDRO-AX', CodMarca: '316' },
  { NomMarca: 'HYSTER', CodMarca: '128' },
  { NomMarca: 'HYSTER CONSTRUCTION', CodMarca: '129' },
  { NomMarca: 'HYUNDAI', CodMarca: '39' },
  { NomMarca: 'IHI', CodMarca: '306' },
  { NomMarca: 'IHI', CodMarca: '324' },
  { NomMarca: 'INGERSOL RAND', CodMarca: '10' },
  { NomMarca: 'INTERNATIONAL', CodMarca: '14' },
  { NomMarca: 'INTERNATIONAL HARVESTER', CodMarca: '130' },
  { NomMarca: 'IPD', CodMarca: '271' },
  { NomMarca: 'ISKRA', CodMarca: '403' },
  { NomMarca: 'ISUZU', CodMarca: '42' },
  { NomMarca: 'ITR', CodMarca: '337' },
  { NomMarca: 'IVECO', CodMarca: '268' },
  { NomMarca: 'J.I.', CodMarca: '98' },
  { NomMarca: 'JACTO', CodMarca: '95' },
  { NomMarca: 'JCB', CodMarca: '8' },
  { NomMarca: 'JEIL', CodMarca: '325' },
  { NomMarca: 'JHON DEERE/YANMAR', CodMarca: '69' },
  { NomMarca: 'JLG', CodMarca: '131' },
  { NomMarca: 'JOHN DEERE AGRICOLA', CodMarca: '219' },
  { NomMarca: 'JOHN DEERE CAÑA', CodMarca: '220' },
  { NomMarca: 'JOHN DEERE CONSTRUCCION', CodMarca: '222' },
  { NomMarca: 'JSW', CodMarca: '377' },
  { NomMarca: 'JUNGHEINRICH', CodMarca: '132' },
  { NomMarca: 'JUNGHEINRICH', CodMarca: '304' },
  { NomMarca: 'K TRACTOR', CodMarca: '80' },
  { NomMarca: 'KALMAR - ALLIS CHALMERS', CodMarca: '133' },
  { NomMarca: 'KATO', CodMarca: '211' },
  { NomMarca: 'KAVAIL', CodMarca: '188' },
  { NomMarca: 'KAWASAKI', CodMarca: '326' },
  { NomMarca: 'KAYABA', CodMarca: '327' },
  { NomMarca: 'KIA', CodMarca: '263' },
  { NomMarca: 'KILLER FILTER', CodMarca: '364' },
  { NomMarca: 'KMP', CodMarca: '76' },
  { NomMarca: 'KOBELCO', CodMarca: '28' },
  { NomMarca: 'KOEHRING', CodMarca: '328' },
  { NomMarca: 'KOHLER MOTORES', CodMarca: '355' },
  { NomMarca: 'KOYO', CodMarca: '234' },
  { NomMarca: 'KUBOTA', CodMarca: '70' },
  { NomMarca: 'LANCER BOSS', CodMarca: '134' },
  { NomMarca: 'LANDINI', CodMarca: '135' },
  { NomMarca: 'LANDOLL', CodMarca: '303' },
  { NomMarca: 'LANSING BAGNALL', CodMarca: '136' },
  { NomMarca: 'LAYMOR', CodMarca: '370' },
  { NomMarca: 'LEROY SOMER', CodMarca: '236' },
  { NomMarca: 'LEXUS', CodMarca: '253' },
  { NomMarca: 'LIEBHERR', CodMarca: '203' },
  { NomMarca: 'LIFE PRODUCTS', CodMarca: '137' },
  { NomMarca: 'LINCOLN', CodMarca: '37' },
  { NomMarca: 'LINDE', CodMarca: '295' },
  { NomMarca: 'LINKBELT', CodMarca: '329' },
  { NomMarca: 'LION LIFTALL', CodMarca: '138' },
  { NomMarca: 'LLANTA', CodMarca: '256' },
  { NomMarca: 'LLANTAS', CodMarca: '257' },
  { NomMarca: 'LONG', CodMarca: '139' },
  { NomMarca: 'LUBER-FINER', CodMarca: '65' },
  { NomMarca: 'LUFKIN', CodMarca: '408' },
  { NomMarca: 'LULL', CodMarca: '144' },
  { NomMarca: 'MACK', CodMarca: '23' },
  { NomMarca: 'MAHLE', CodMarca: '374' },
  { NomMarca: 'MAINERO', CodMarca: '280' },
  { NomMarca: 'MANITOU', CodMarca: '145' },
  { NomMarca: 'MANN', CodMarca: '62' },
  { NomMarca: 'MARCHESAN', CodMarca: '93' },
  { NomMarca: 'MASSEY FERGUSON', CodMarca: '146' },
  { NomMarca: 'MAXIFORCE', CodMarca: '31' },
  { NomMarca: 'MAXXIS', CodMarca: '82' },
  { NomMarca: 'MAZDA', CodMarca: '147' },
  { NomMarca: 'MCBEE', CodMarca: '275' },
  { NomMarca: 'MCCORMICK', CodMarca: '148' },
  { NomMarca: 'MCMASTER-CARR', CodMarca: '395' },
  { NomMarca: 'MEMO', CodMarca: '285' },
  { NomMarca: 'MERCEDES BENZ', CodMarca: '318' },
  { NomMarca: 'METSO', CodMarca: '242' },
  { NomMarca: 'MIBA', CodMarca: '229' },
  { NomMarca: 'MIBA', CodMarca: '187' },
  { NomMarca: 'MICHIGAN', CodMarca: '276' },
  { NomMarca: 'MILLER', CodMarca: '266' },
  { NomMarca: 'MILLER FLUID', CodMarca: '292' },
  { NomMarca: 'MILWAUKEE', CodMarca: '405' },
  { NomMarca: 'MINN PAR', CodMarca: '149' },
  { NomMarca: 'MISWACO', CodMarca: '386' },
  { NomMarca: 'MITSUBISHI', CodMarca: '33' },
  { NomMarca: 'MOBILE DRILL', CodMarca: '150' },
  { NomMarca: 'MOLDMIX', CodMarca: '230' },
  { NomMarca: 'MOTOR MWM', CodMarca: '205' },
  { NomMarca: 'MOTORCRAFT', CodMarca: '52' },
  { NomMarca: 'MOXY', CodMarca: '382' },
  { NomMarca: 'MURPHY', CodMarca: '250' },
  { NomMarca: 'MWM', CodMarca: '319' },
  { NomMarca: 'N/A', CodMarca: '198' },
  { NomMarca: 'NACHI', CodMarca: '350' },
  { NomMarca: 'NATIONAL', CodMarca: '77' },
  { NomMarca: 'NAVISTAR', CodMarca: '67' },
  { NomMarca: 'NEW HOLLAND', CodMarca: '18' },
  { NomMarca: 'NEWCO', CodMarca: '35' },
  { NomMarca: 'NISSAN', CodMarca: '151' },
  { NomMarca: 'NQAS', CodMarca: '36' },
  { NomMarca: 'NSK', CodMarca: '351' },
  { NomMarca: 'NTN', CodMarca: '26' },
  { NomMarca: 'OEM', CodMarca: '195' },
  { NomMarca: 'OILGEAR', CodMarca: '301' },
  { NomMarca: 'OLIVER WHITE FARM', CodMarca: '152' },
  { NomMarca: 'OLYMPIAN', CodMarca: '363' },
  { NomMarca: 'OMEGA', CodMarca: '362' },
  { NomMarca: 'OPTIBELT', CodMarca: '349' },
  { NomMarca: 'ORIGINAL', CodMarca: '53' },
  { NomMarca: 'OTH', CodMarca: '186' },
  { NomMarca: 'P & H CRANE', CodMarca: '153' },
  { NomMarca: 'PAI', CodMarca: '277' },
  { NomMarca: 'PALFINGER', CodMarca: '298' },
  { NomMarca: 'PAN', CodMarca: '208' },
  { NomMarca: 'PANEGOSSI', CodMarca: '78' },
  { NomMarca: 'PANGOLIN', CodMarca: '402' },
  { NomMarca: 'PARKER', CodMarca: '286' },
  { NomMarca: 'PARSONS', CodMarca: '154' },
  { NomMarca: 'PAYHAULER', CodMarca: '378' },
  { NomMarca: 'PERKINS', CodMarca: '9' },
  { NomMarca: 'PERKINS/MWM', CodMarca: '91' },
  { NomMarca: 'PETTIBONE', CodMarca: '155' },
  { NomMarca: 'PHILIFT', CodMarca: '156' },
  { NomMarca: 'POWER BATTERY', CodMarca: '339' },
  { NomMarca: 'PPP ENGINEERING', CodMarca: '254' },
  { NomMarca: 'PRENTICE', CodMarca: '379' },
  { NomMarca: 'PRIMEX', CodMarca: '24' },
  { NomMarca: 'PRODIMSA', CodMarca: '83' },
  { NomMarca: 'PROMOVE', CodMarca: '29' },
  { NomMarca: 'PUTZMEISTER', CodMarca: '216' },
  { NomMarca: 'QUINCY', CodMarca: '281' },
  { NomMarca: 'R.I.', CodMarca: '201' },
  { NomMarca: 'RACOR', CodMarca: '368' },
  { NomMarca: 'RADIOSPARES', CodMarca: '406' },
  { NomMarca: 'RANDON', CodMarca: '204' },
  { NomMarca: 'RAYMOND', CodMarca: '157' },
  { NomMarca: 'REEMPLAZO', CodMarca: '3' },
  { NomMarca: 'REGAL', CodMarca: '54' },
  { NomMarca: 'REX', CodMarca: '158' },
  { NomMarca: 'REXROTH', CodMarca: '267' },
  { NomMarca: 'ROCKFORD', CodMarca: '159' },
  { NomMarca: 'RODA TRACK', CodMarca: '265' },
  { NomMarca: 'RODAMIENTO AGCO', CodMarca: '92' },
  { NomMarca: 'ROYAL TRACTOR', CodMarca: '160' },
  { NomMarca: 'RS COMPONENTS', CodMarca: '394' },
  { NomMarca: 'RT', CodMarca: '314' },
  { NomMarca: 'SABO', CodMarca: '346' },
  { NomMarca: 'SACI', CodMarca: '87' },
  { NomMarca: 'SAMSUNG', CodMarca: '330' },
  { NomMarca: 'SANDEN', CodMarca: '373' },
  { NomMarca: 'SANDERSON', CodMarca: '161' },
  { NomMarca: 'SANDVICK', CodMarca: '297' },
  { NomMarca: 'SANY', CodMarca: '371' },
  { NomMarca: 'SANZ', CodMarca: '184' },
  { NomMarca: 'SAUER DANFOSS', CodMarca: '300' },
  { NomMarca: 'SCANIA', CodMarca: '231' },
  { NomMarca: 'SCAT TRAK', CodMarca: '336' },
  { NomMarca: 'SCAT TRUCK', CodMarca: '335' },
  { NomMarca: 'SCHMERSAL', CodMarca: '309' },
  { NomMarca: 'SCHNEIDER', CodMarca: '367' },
  { NomMarca: 'SCHWING', CodMarca: '264' },
  { NomMarca: 'SDMO', CodMarca: '244' },
  { NomMarca: 'SELLICK', CodMarca: '162' },
  { NomMarca: 'SHELL', CodMarca: '84' },
  { NomMarca: 'SHUTTLE LIFT', CodMarca: '163' },
  { NomMarca: 'SILENT HOIST', CodMarca: '164' },
  { NomMarca: 'SIOUX', CodMarca: '393' },
  { NomMarca: 'SKF', CodMarca: '345' },
  { NomMarca: 'SKF TMAS', CodMarca: '218' },
  { NomMarca: 'SKYTRAK', CodMarca: '165' },
  { NomMarca: 'SLP', CodMarca: '284' },
  { NomMarca: 'SPAREX', CodMarca: '400' },
  { NomMarca: 'SPOT', CodMarca: '55' },
  { NomMarca: 'STAMFORD', CodMarca: '235' },
  { NomMarca: 'STANADYNE', CodMarca: '248' },
  { NomMarca: 'STANLEY', CodMarca: '305' },
  { NomMarca: 'STANLEY', CodMarca: '238' },
  { NomMarca: 'STEYR', CodMarca: '166' },
  { NomMarca: 'STORK', CodMarca: '392' },
  { NomMarca: 'SUBARO INDUSTRIAL', CodMarca: '340' },
  { NomMarca: 'SUBARU', CodMarca: '47' },
  { NomMarca: 'SUBOTA', CodMarca: '57' },
  { NomMarca: 'SULLAIR', CodMarca: '251' },
  { NomMarca: 'SUMITOMO', CodMarca: '331' },
  { NomMarca: 'SUNDSTRAND', CodMarca: '293' },
  { NomMarca: 'SURE', CodMarca: '59' },
  { NomMarca: 'SUZUKI', CodMarca: '369' },
  { NomMarca: 'TADANO/MANTIS', CodMarca: '272' },
  { NomMarca: 'TAILIFT', CodMarca: '167' },
  { NomMarca: 'TAIWAN', CodMarca: '270' },
  { NomMarca: 'TAKEUCHI', CodMarca: '332' },
  { NomMarca: 'TAKEUCHI', CodMarca: '206' },
  { NomMarca: 'TCI', CodMarca: '168' },
  { NomMarca: 'TCM', CodMarca: '169' },
  { NomMarca: 'TECFIL', CodMarca: '63' },
  { NomMarca: 'TEREX', CodMarca: '22' },
  { NomMarca: 'THERMOKING', CodMarca: '311' },
  { NomMarca: 'THOMAS', CodMarca: '240' },
  { NomMarca: 'TIMKEN', CodMarca: '56' },
  { NomMarca: 'TOYOTA', CodMarca: '170' },
  { NomMarca: 'TRACKMOBILE', CodMarca: '171' },
  { NomMarca: 'TRASTEEL', CodMarca: '315' },
  { NomMarca: 'TROJAN', CodMarca: '172' },
  { NomMarca: 'TS', CodMarca: '278' },
  { NomMarca: 'TUG', CodMarca: '173' },
  { NomMarca: 'TWIN DISC', CodMarca: '174' },
  { NomMarca: 'UNDOTH', CodMarca: '183' },
  { NomMarca: 'UNITEC', CodMarca: '210' },
  { NomMarca: 'USA', CodMarca: '88' },
  { NomMarca: 'VAPORMATIC', CodMarca: '175' },
  { NomMarca: 'VDO', CodMarca: '322' },
  { NomMarca: 'VICKERS', CodMarca: '21' },
  { NomMarca: 'VOGELE', CodMarca: '282' },
  { NomMarca: 'VOLVO', CodMarca: '11' },
  { NomMarca: 'VOLVO PENTA', CodMarca: '353' },
  { NomMarca: 'WABCO', CodMarca: '228' },
  { NomMarca: 'WACKER NEUSON', CodMarca: '359' },
  { NomMarca: 'WAUKESHA', CodMarca: '17' },
  { NomMarca: 'WEG', CodMarca: '372' },
  { NomMarca: 'WG', CodMarca: '247' },
  { NomMarca: 'WHITE MOTORS', CodMarca: '176' },
  { NomMarca: 'WIGGINS', CodMarca: '177' },
  { NomMarca: 'WILSON', CodMarca: '380' },
  { NomMarca: 'WINDHAM', CodMarca: '178' },
  { NomMarca: 'WIRTGEN', CodMarca: '224' },
  { NomMarca: 'WIRTHCO', CodMarca: '245' },
  { NomMarca: 'WIX', CodMarca: '64' },
  { NomMarca: 'XCMG', CodMarca: '207' },
  { NomMarca: 'XTREME TELEHANDLERS', CodMarca: '179' },
  { NomMarca: 'YALE', CodMarca: '180' },
  { NomMarca: 'YAMAHA', CodMarca: '360' },
  { NomMarca: 'YANMAR', CodMarca: '68' },
  { NomMarca: 'YANMAR MARINE', CodMarca: '354' },
  { NomMarca: 'YELLOW', CodMarca: '185' },
  { NomMarca: 'YUTANI', CodMarca: '333' },
  { NomMarca: 'ZETOR', CodMarca: '181' },
  { NomMarca: 'ZEXEL', CodMarca: '397' },
  { NomMarca: 'ZF', CodMarca: '94' },
  { NomMarca: 'ZF INDUSTRIES', CodMarca: '182' },
];

export default (state = initState, action) => {
  if (action.type === 'MARCAS_ACTION') {
    return action.payload;
  } else {
    return state;
  }
};
